[2023-10-22T05:14:07.297+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T05:14:06.457136+00:00 [queued]>
[2023-10-22T05:14:07.307+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T05:14:06.457136+00:00 [queued]>
[2023-10-22T05:14:07.308+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T05:14:07.323+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): task1> on 2023-10-22 05:14:06.457136+00:00
[2023-10-22T05:14:07.328+0000] {standard_task_runner.py:57} INFO - Started process 336 to run task
[2023-10-22T05:14:07.331+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'task1', 'manual__2023-10-22T05:14:06.457136+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmps_k6eb0g']
[2023-10-22T05:14:07.333+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask task1
[2023-10-22T05:14:07.368+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.task1 manual__2023-10-22T05:14:06.457136+00:00 [running]> on host 0a51e56afb27
[2023-10-22T05:14:07.407+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'task1', field 'command'. Template: 'cd /home/vertikal/data_science/web_scrap/rumah/rumah && bash script2.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: cd /home/vertikal/data_science/web_scrap/rumah/rumah && bash script2.sh
[2023-10-22T05:14:07.408+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: cd /home/vertikal/data_science/web_scrap/rumah/rumah && bash script2.sh
[2023-10-22T05:14:07.415+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=task1, execution_date=20231022T051406, start_date=20231022T051407, end_date=20231022T051407
[2023-10-22T05:14:07.425+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task task1 (cd /home/vertikal/data_science/web_scrap/rumah/rumah && bash script2.sh; 336)
[2023-10-22T05:14:07.464+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T05:14:07.477+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
