[2023-10-27T09:20:35.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T09:08:27.929557+00:00 [queued]>
[2023-10-27T09:20:35.707+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T09:08:27.929557+00:00 [queued]>
[2023-10-27T09:20:35.707+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-27T09:20:35.719+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): pull_and_clean_data_evidently> on 2023-10-27 09:08:27.929557+00:00
[2023-10-27T09:20:35.726+0000] {standard_task_runner.py:57} INFO - Started process 851 to run task
[2023-10-27T09:20:35.728+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'pull_and_clean_data_evidently', 'manual__2023-10-27T09:08:27.929557+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpvo8o9hvq']
[2023-10-27T09:20:35.731+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask pull_and_clean_data_evidently
[2023-10-27T09:20:35.765+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T09:08:27.929557+00:00 [running]> on host 981d0f90760c
[2023-10-27T09:20:35.830+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='pull_and_clean_data_evidently' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T09:08:27.929557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-27T09:08:27.929557+00:00'
[2023-10-27T09:20:35.839+0000] {base.py:73} INFO - Using connection ID 'postgres_docker' for task execution.
[2023-10-27T09:20:35.856+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-27T09:20:36.302+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-27T09:20:36.310+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=pull_and_clean_data_evidently, execution_date=20231027T090827, start_date=20231027T092035, end_date=20231027T092036
[2023-10-27T09:20:36.342+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-27T09:20:36.358+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
