[2023-10-27T08:48:25.039+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T08:48:22.715736+00:00 [queued]>
[2023-10-27T08:48:25.051+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T08:48:22.715736+00:00 [queued]>
[2023-10-27T08:48:25.052+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-27T08:48:25.072+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): pull_and_clean_data_evidently> on 2023-10-27 08:48:22.715736+00:00
[2023-10-27T08:48:25.084+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2023-10-27T08:48:25.087+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'pull_and_clean_data_evidently', 'manual__2023-10-27T08:48:22.715736+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpfnczp9m0']
[2023-10-27T08:48:25.091+0000] {standard_task_runner.py:85} INFO - Job 182: Subtask pull_and_clean_data_evidently
[2023-10-27T08:48:25.150+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL.pull_and_clean_data_evidently manual__2023-10-27T08:48:22.715736+00:00 [running]> on host 45cd7075ee11
[2023-10-27T08:48:25.268+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='pull_and_clean_data_evidently' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T08:48:22.715736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-27T08:48:22.715736+00:00'
[2023-10-27T08:48:25.282+0000] {base.py:73} INFO - Using connection ID 'postgres_docker' for task execution.
[2023-10-27T08:48:25.308+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-27T08:48:25.963+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-27T08:48:25.980+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=pull_and_clean_data_evidently, execution_date=20231027T084822, start_date=20231027T084825, end_date=20231027T084825
[2023-10-27T08:48:26.024+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-27T08:48:26.047+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
